version: '3'

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: food-delivery
      MYSQL_USER: food-delivery
      MYSQL_PASSWORD: 12345